# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'index.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(399, 300)
        Dialog.setStyleSheet("background-color: #31364E;")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(170, 250, 81, 31))
        self.pushButton.setStyleSheet("QPushButton {\n"
"    font: 75 11pt \"Century Gothic\";\n"
"    color: #00CC00;\n"
"    background-color: #27292E;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    color: #00FF00;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    color: #009900;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 80, 91, 16))
        self.label.setStyleSheet("color: #ccc;\n"
"font: 5 8pt \"Century Gothic\";\n"
"")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(Dialog)
        self.lineEdit.setGeometry(QtCore.QRect(140, 70, 31, 41))
        self.lineEdit.setStyleSheet("color: #FFFF33;\n"
"font: 14pt \"Century Gothic\";\n"
"background-color: #27292E;\n"
"border: none;\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 140, 111, 16))
        self.label_2.setStyleSheet("color: #ccc;\n"
"font: 5 8pt \"Century Gothic\";\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(120, 10, 151, 41))
        self.label_3.setStyleSheet("color: #ccc;\n"
"font: 5 22pt \"Century Gothic\";\n"
"")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(340, 280, 47, 13))
        self.label_4.setStyleSheet("color: #ccc;\n"
"font: 5 8pt \"Century Gothic\";\n"
"")
        self.label_4.setObjectName("label_4")
        self.lineEdit_2 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_2.setGeometry(QtCore.QRect(140, 130, 31, 41))
        self.lineEdit_2.setStyleSheet("color: #FFFF33;\n"
"font: 14pt \"Century Gothic\";\n"
"background-color: #27292E;\n"
"border: none;\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(40, 200, 271, 21))
        self.label_5.setStyleSheet("color: #ccc;\n"
"font: 5 8pt \"Century Gothic\";\n"
"")
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton.setText(_translate("Dialog", "Запуск"))
        self.label.setText(_translate("Dialog", "Кнопка запуска"))
        self.label_2.setText(_translate("Dialog", "Кнопка остановки"))
        self.label_3.setText(_translate("Dialog", "MyPyClick"))
        self.label_4.setText(_translate("Dialog", "version: 1"))
        self.label_5.setText(_translate("Dialog", "Статус:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
